name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Get version using GitTools
        id: gitversion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
            versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Adjust version suffix for stage branch
        id: adjust_version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/stage" ]; then
            VERSION="${{ steps.version_step.outputs.FullSemVer }}-preview"
          else
            VERSION="${{ steps.version_step.outputs.FullSemVer }}"
          fi
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Create artifacts directory
        run: mkdir -p ./artifacts

      - name: Pack NuGet Package
        run: |
          dotnet pack --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.adjust_version.outputs.version }}
      
      - name: List artifacts folder
        run: ls -la ./artifacts
      
      - name: Publish NuGet Package
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage'
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
